### PR TITLE
add stmts for new order and payment

### PR DESCRIPTION
**Pull request by siddontang**
Use prepared statements for new order and payment. 

We can support order status, stock level, and delivery later. 

I have run for a while and then use `check` to pass the consistency check.

### CODE REVIEW

**Comment by siddontang** [comment]
There is a problem for new cluster, I will fix it ASAP.

**Comment by mahjonp** [comment]
I'm curious about how much improvement of tpmC does this PR bring when you test?

**Comment by siddontang** [comment]
this definitely can reduce the cost of TiDB, but I have not tested in a big cluster, you can help me do it. 

IMO, we should do it as other TPCC tests do. @mahjonp

**Comment by mahjonp** [comment]
> this definitely can reduce the cost of TiDB, but I have not tested in a big cluster, you can help me do it.
> 
> IMO, we should do it as other TPCC tests do. @mahjonp

OK, I will test it on a bigger cluster.

**Pull request merged**
