### PR TITLE
use table output for better user experience

### PR DESCRIPTION
**Pull request by sillydong**
Hi all, I'm working on this PR to give a try for outputting the result as table style. Originally, the output is a line and not aligned. With table style output, we can get better user experience and it can be much more convenient to copy values.

The output would like this:
image

in comparison, the original output is like this:
image

This is a simple try and I have not written it in a better way. I would first like to get some feedback on this approach and later I can make it better.

Any feedback is welcomed.

### CODE REVIEW

**Comment by sillydong** [comment]
Beside this approach with `tablewriter`, we can also do some manual alignment with `fmt.Sprintf` and fixed string size to make it better. But that's a little more inconvenient. What do you think?

**Comment by siddontang** [comment]
cool, maybe it is better to provide an output format flag, like table or origin raw message? so we can further support  JSON, etc. 

Another thing maybe we already used some scripts to parse the output results in our CI, so here we need to ensure the compatibility.

**Comment by siddontang** [comment]
maybe we can also support this in https://github.com/pingcap/go-ycsb 

@sillydong can you have a try later?

**Comment by sillydong** [comment]
> 

Seems like they are similar tools. If this approach has no problem, I will make it more formal and update this PR. 
After we merge this PR I can do it again in go-ycsb.

**Comment by sillydong** [comment]
> cool, maybe it is better to provide an output format flag, like table or origin raw message? so we can further support JSON, etc.

I will try adding a flag `output` to control the output style, available values may be `table`,`plaintext`,`json`, the default will be `table` for human read. Is this OK?

> Another thing maybe we already used some scripts to parse the output results in our CI, so here we need to ensure the compatibility.

Could you share more detail about the CI? I didn't find any thing for that, only a test case in `hist_test.go`. Is there anything more?

**Comment by siddontang** [comment]
@sillydong 

> I will try adding a flag output to control the output style, available values may be table,plaintext,json, the default will be table for human read. Is this OK?

Fine, but IMO I prefer plain instead of plaintext :-)

For CI, means PingCAP's internal CI or bench system, has not been public.

**Comment by dbsid** [comment]
> 



> > cool, maybe it is better to provide an output format flag, like table or origin raw message? so we can further support JSON, etc.
> 
> I will try adding a flag `output` to control the output style, available values may be `table`,`plaintext`,`json`, the default will be `table` for human read. Is this OK?
> 
> > Another thing maybe we already used some scripts to parse the output results in our CI, so here we need to ensure the compatibility.
> 
> Could you share more detail about the CI? I didn't find any thing for that, only a test case in `hist_test.go`. Is there anything more?

Inside PingCap, we've scripts to interpret the go-tpc result based on the current output format, please make the current format as the default for compatibility.

**Comment by sillydong** [comment]
OK, the value would be `plain`,`table`,`json`, and default is `plain`. 

For CI part, you may add cases for new formats after this.

**Comment by siddontang** [comment]
any update? @sillydong

**Comment by sillydong** [comment]
not yet, will update tonight

**Comment by sillydong** [comment]
here are some snapshots

plain
image

table
image

json
image

**Review by dbsid — APPROVED** [review]

**Comment by sillydong** [comment]
updated the go.mod

**Comment by siddontang** [comment]
thanks @sillydong 

can you do the same thing for go-ycsb?

**Comment by sillydong** [comment]
working on learning the detail of go-ycsb, may take some time

**Pull request merged**
